### ISSUE TITLE
JSON readtable error

### ISSUE THREAD

**Issue by guibor** [astoff/code-cells.el#29] opened 2024-06-21 15:23 UTC
I get the following error:

"json-read: JSON readtable error:"

whenever I run `code-cells-convert-ipynb()`

backtrace

```
Debugger entered--Lisp error: (json-readtable-error 35)
  signal(json-readtable-error (35))
  json-read()
  code-cells--guess-mode()
  code-cells-convert-ipynb()
 ```

**Comment by astoff** [comment] 2024-10-03 10:33
I can't reproduce, but this should be fixed in 498edb3.

**Closed by astoff** 2024-10-03 10:33 UTC
